### PR TITLE
Wrap up unit tests

### PR DESCRIPTION
**Pull request by Brofessional**
Finish up the unit tests

### CODE REVIEW

**Comment by jti-lanl** [comment]
Don’t forget about the need to generate a .h file, containing C struct declarations, if the fields of the abstract XML change.  Perhaps we can just do that by hand, from now on.

**Comment by Brofessional** [comment]
addresses #3

**Comment by Brofessional** [comment]
@jti-lanl 
I believe the plan for the future is to maintain static config headers for MarFS. The config structs don't change terribly often for MarFS, but I have some stuff in place that I could maybe use for generating a new header file with updated structs from python if the structs change. I used something similar to that in the early phases for rapid prototypes, it could still have value for that purpose. I'll open an issue.

**Comment by jti-lanl** [comment]
Your approach is probably good.  Like you said, the structure isn’t changing much these days.

**Pull request merged**
